### ISSUE TITLE
Create a list of films and most popular trope associated

### ISSUE THREAD

**Issue by jcarpio** [jcarpio/tropes2vec#26]
The idea here is create a list to check accuracy in embedding vectors models.
Similar to this one:
Boston Boston_Globe New_York New_Work_Times

Most times that apear Boston and newspaper related infomation in text corpus have to appear Boston_Globe newspaper, and probably more important Boston_Globe only appear in contexts associated to Boston and newspaper an not in other contexts.

It is possible to obtain something similar with tropes?

Problably if we modify trope name to include film name we will obtain the same. And then a way to associate trope name with his new trope-film name.

film1 is a film1_trope1 as film2 is a film2_trope2
trope1 is film1_trope1 as trope2 is a film2_trope2

in this way we can create a relationship between film and film_trope and other association between
trope and film_trope name

**Comment by JJ** [comment]
How does this contribute to the objective of the paper?

**Comment by jcarpio** [comment]
I think we need a way to check accuracy of embedding vectors created. To do that wor2vec authors created a checking list manually if items that have to be related like example of newspaper.
I am traying to do the same with tropes and films.

**Comment by jcarpio** [comment]
With this accuracy, we can demonstrate that out artificial created corpus have sense.

**Comment by jcarpio** [comment]
Once accuracy is good enough we can use embedding vectors model to other tasks like obtain a vector that represent a film and so on. But if accuracy is not good, other tasks probably have will have no sense.

**Comment by JJ** [comment]
It's better to just use tropes and its arithmetic (as another issue says).
But whatever.

**Comment by jcarpio** [comment]
In a text created by humans probably do no have sense to talk about Boston_Globe newspaper if we are talking about Granada (probably one extrange case yes, but usually not). But with an artificial created corupus we have to paid special atention about where we are writing some terms. Otherwise, we can create artificial relationships that have no sense. Frecuency of terms writed together are also crucial, stronger relationships have to be writed more times to obtain a good model. For this reason I think will be interesting have a ranking of tropes, and most populars have to appear more times than less popular ones.

**Comment by jcarpio** [comment]
The idea of permutations are appliying same weght to all tropes, and I want to check with the strategy of accuracy what combination of tropes and films works better. For example if is better to write more times combinations of films with most popular tropes.

**Comment by JJ** [comment]
You will need to justify that in the context of the paper and its
objectives. And there's enough to work on (and write) without getting into
this.
