### ISSUE TITLE
Why do you use word2vec instead of gensim?

### ISSUE THREAD

**Issue by JJ** [jcarpio/tropes2vec#30]
Are they not the same?

**Comment by jcarpio** [comment]
word2vec original package is easier to launch examples and included some tools as accuracy check programs. As I know, gensim include a word2vec implementation in python with tools to create and manipulate word2vec embedding vectors files. I think it is possible to do the same with both, but word2vec package is more clear and easier. We use both word2vec package to create bin files and gensim to do some operations with them.

**Comment by jcarpio** [comment]
We use both of them.
